package gui;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;
import controller.Controller;
import gui.panels.TavoliPanel;

import javax.swing.*;
import java.awt.*;

public class MainFrame extends JFrame {

    private JPanel pannelloCentrale;
    private JPanel pannelloContenuto;
    private JPanel pannelloPulsanti;

    private JButton dashboardButton;
    private JButton menuButton;
    private JButton ordiniButton;
    private JButton prenotazioniButton;
    private JButton tavoliButton;
    private JButton staffButton;
    private JButton settingsButton;

    private Controller controller; // riferimento al controller

    public MainFrame(Controller controller) {
        this.controller = controller;

        setContentPane(pannelloCentrale);
        setTitle("Gestione Ristorante");
        setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        setSize(900, 600);
        setLocationRelativeTo(null);

        collegaPulsanti();

        setVisible(true);
    }

    private void collegaPulsanti() {
        TavoliPanel tavoliPanel = new TavoliPanel(controller);

        tavoliButton.addActionListener(e -> impostaPannello(tavoliPanel));

        // Gli altri per ora mostrano solo un messaggio
        dashboardButton.addActionListener(e -> mostraMessaggio("Dashboard - Lavori in corso"));
        menuButton.addActionListener(e -> mostraMessaggio("Menu - Lavori in corso"));
        ordiniButton.addActionListener(e -> mostraMessaggio("Ordini - Lavori in corso"));
        prenotazioniButton.addActionListener(e -> mostraMessaggio("Prenotazioni - Lavori in corso"));
        staffButton.addActionListener(e -> mostraMessaggio("Staff - Lavori in corso"));
        settingsButton.addActionListener(e -> mostraMessaggio("Settings - Lavori in corso"));
    }

    public void impostaPannello(JPanel pannello) {
        pannelloContenuto.removeAll();
        pannelloContenuto.add(pannello, BorderLayout.CENTER);
        pannelloContenuto.revalidate();
        pannelloContenuto.repaint();
    }

    private void mostraMessaggio(String msg) {
        JPanel temp = new JPanel(new BorderLayout());
        JLabel label = new JLabel(msg, SwingConstants.CENTER);
        label.setFont(new Font("Arial", Font.ITALIC, 18));
        temp.add(label, BorderLayout.CENTER);
        impostaPannello(temp);
    }









    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        pannelloCentrale = new JPanel();
        pannelloCentrale.setLayout(new BorderLayout(0, 0));
        pannelloContenuto = new JPanel();
        pannelloContenuto.setLayout(new BorderLayout(0, 0));
        pannelloCentrale.add(pannelloContenuto, BorderLayout.EAST);
        pannelloPulsanti = new JPanel();
        pannelloPulsanti.setLayout(new GridLayoutManager(8, 1, new Insets(0, 0, 0, 0), -1, -1));
        pannelloCentrale.add(pannelloPulsanti, BorderLayout.WEST);
        dashboardButton = new JButton();
        dashboardButton.setText("Dashboard");
        pannelloPulsanti.add(dashboardButton, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        pannelloPulsanti.add(spacer1, new GridConstraints(6, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_VERTICAL, 1, GridConstraints.SIZEPOLICY_WANT_GROW, null, null, null, 0, false));
        ordiniButton = new JButton();
        ordiniButton.setText("Ordini");
        pannelloPulsanti.add(ordiniButton, new GridConstraints(2, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        prenotazioniButton = new JButton();
        prenotazioniButton.setText("Prenotazioni");
        pannelloPulsanti.add(prenotazioniButton, new GridConstraints(3, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        tavoliButton = new JButton();
        tavoliButton.setText("Tavoli");
        pannelloPulsanti.add(tavoliButton, new GridConstraints(4, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        settingsButton = new JButton();
        settingsButton.setText("Settings");
        pannelloPulsanti.add(settingsButton, new GridConstraints(7, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        menuButton = new JButton();
        menuButton.setText("Menu");
        pannelloPulsanti.add(menuButton, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        staffButton = new JButton();
        staffButton.setText("Staff");
        pannelloPulsanti.add(staffButton, new GridConstraints(5, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return pannelloCentrale;
    }

}
